name: "fase-state-management"
description: "Core workflow voor fase state management en context preservation in VBD ecosystem"

metadata:
  author: "Master Orchestrator"
  version: "1.0"
  last-updated: "2025-10-11"
  module: "value-ecosystem-design"
  framework: "Fase 2A - Orchestration Core"
  estimated-duration: "15-20 min"
  dependencies: ["canvas-orchestrator", "ecosystem-planner"]

variables:
  - user_name: "{user_name}"
  - master_orchestrator_role: "Chief Fase Conductor"
  - current_fase: "canvas_foundation"
  - fase_progress: 0
  - completion_status: "draft"
  - global_context: {}
  - fase_context: {}
  - transition_artifacts: []
  - system_status: "initializing"

steps:
  - id: "fase-state-initialization"
    name: "Initialize Fase State Management"
    description: "Opstarten van fase state tracking en context stores"
    duration: "2 min"
    outputs: ["current_fase", "fase_progress", "system_status"]
    instructions: |
      Initialize de fase state management system:

      **Fase State Setup:**
      - Detect current fase (canvas_foundation | ecosystem_realization)
      - Load phase progress (0-100%)
      - Set completion status (draft | validated | approved)

      **Context Store Initialization:**
      - Initialize global context store (persistent across fases)
      - Create fase-specific context store
      - Load any existing transition artifacts

      **System Status Verification:**
      - Check orchestration health
      - Validate context preservation
      - Confirm transition protocols ready

  - id: "context-preservation-setup"
    name: "Establish Context Preservation Framework"
    description: "Setup framework voor cross-fase context management"
    duration: "3 min"
    inputs: ["global_context", "fase_context"]
    outputs: ["context_preservation_status"]
    instructions: |
      Establish robust context preservation:

      **Global Context Management:**
      - User preferences en work style
      - Project history en learnings
      - Stakeholder relationships foundation
      - Tool preferences en workflow patterns

      **Fase Context Management:**
      - Canvas elements preservation
      - Ecosystem planning continuity
      - Interactive session insights
      - Iteration triggers en rationale

      **Transition Artifacts:**
      - Canvas deliverables package
      - Ecosystem input requirements
      - Quality gates validation
      - Iteration points identification

  - id: "transition-protocol-configuration"
    name: "Configure Fase Transition Protocols"
    description: "Setup protocols voor seamless fase-overgangen"
    duration: "3 min"
    inputs: ["current_fase", "fase_progress"]
    outputs: ["transition_protocols_status"]
    instructions: |
      Configure transition orchestration:

      **Canvas to Ecosystem Transition:**
      - Preconditions: canvas_completion >= 90
      - Data mapping: PVC → Ecosystem inputs
      - Validation gates: stakeholder commitment, capacity assessment
      - Handoff protocols: deliverable package transfer

      **Ecosystem to Canvas Iteration:**
      - Trigger conditions: validation failure, insight gaps
      - Context rollback: preserve valuable insights
      - Learning integration: improvement suggestions
      - Restart protocols: minimal disruption flow

      **Interactive Enhancement:**
      - Always-available agent access
      - Context sharing in collaborative sessions
      - Insight aggregation across fase boundaries

  - id: "checkpoint-and-recovery-setup"
    name: "Establish Checkpoint and Recovery Mechanisms"
    description: "Setup system resilience en recovery capabilities"
    duration: "2 min"
    inputs: ["system_status"]
    outputs: ["recovery_capabilities"]
    instructions: |
      Establish system resilience:

      **Checkpoint System:**
      - Automatic checkpoints per major fase milestone
      - Manual save points op user request
      - Context snapshots voor rollback capabilities

      **Recovery Mechanisms:**
      - Context reconstruction from artifacts
      - Fase state restoration from checkpoints
      - Graceful degradation bij system issues
      - User-guided recovery workflows

      **Data Integrity:**
      - Redundant storage van critical context
      - Validation van checkpoint integrity
      - Audit trail van alle state changes

  - id: "interactive-protocol-gateway"
    name: "Initialize Interactive Agent Access Gateway"
    description: "Setup gateway voor direct agent conversations"
    duration: "3 min"
    inputs: ["transition_protocols_status"]
    outputs: ["interactive_gateway_status"]
    instructions: |
      Initialize interactive capabilities:

      **Direct Agent Routing:**
      - Map commands to CIS agents
      - Context sharing protocols
      - Session management setup

      **Party Mode Coordination:**
      - Multi-agent orchestration setup
      - Collaborative session protocols
      - Insight aggregation frameworks

      **Human Oversight Integration:**
      - Always-enabled human control
      - Transparent AI decision logging
      - Intervention points voor alle major actions

  - id: "orchestration-dashboard-setup"
    name: "Configure Orchestration Dashboard and Monitoring"
    description: "Setup monitoring en user interface voor orchestration"
    duration: "2 min"
    inputs: ["recovery_capabilities", "interactive_gateway_status"]
    outputs: ["dashboard_ready", "system_fully_operational"]
    instructions: |
      Final orchestration system configuration:

      **Dashboard Components:**
      - Real-time fase progress visualization
      - Context preservation status
      - Transition readiness indicators
      - Interactive access portal

      **Monitoring System:**
      - Fase state change alerts
      - Context integrity checks
      - Transition success metrics
      - Interactive session analytics

      **User Interface:**
      - Command interface voor orchestration actions
      - Status overview van alle subsystems
      - Guided workflows voor fase transitions
      - Intelligent suggestions gebaseerd op context

deliverables:
  - "Fase State Management System": "Operational fase tracking en progress monitoring"
  - "Context Preservation Framework": "Cross-fase context management capability"
  - "Transition Protocol Suite": "Seamless fase handoff mechanisms"
  - "Interactive Agent Gateway": "Direct access routing en session management"
  - "Orchestration Dashboard": "Real-time system monitoring en control interface"

success-criteria:
  - Fase state management volledig operationeel met 100% state tracking
  - Context preservation verified met successful recovery tests
  - Transition protocols geconfigureerd voor alle fase-overgangen
  - Interactive gateway operationeel met agent routing actief
  - Orchestration dashboard live met real-time monitoring

validation-checklist:
  - [ ] Fase state tracking accurate en real-time bijgewerkt
  - [ ] Context preservation werkt bij fase switches (test recovery)
  - [ ] Transition protocols succesvol bij manual testing
  - [ ] Interactive gateway routeert commands naar correcte agents
  - [ ] Dashboard toont accurate system status en metrics

template: "{installed_path}/orchestration-dashboard-template.md"
