name: "PVC Stakeholder Analysis Workflow"
description: "Conduct comprehensive stakeholder analysis with public values alignment"

metadata:
  author: "PVC Agent"
  version: "1.0"
  last-updated: "2025-01-09"
  module: "BMM"
  framework: "PVC-VSD-Empirical Research"
  estimated-duration: "2-3 days"
  cis-integration: "design-thinking-coach, storyteller"

variables:
  - user_name: "{user_name}"
  - stakeholder_initial: []
  - public_values_inventory: []
  - power_interest_matrix: {}
  - values_alignment_analysis: {}
  - output_folder: "{output_folder}"

steps:
  - id: "preparation-1"
    name: "Analysis Framework Setup"
    description: "Establish comprehensive stakeholder analysis framework with public values integration"
    duration: "1 hour"
    inputs: []
    outputs:
      - analysis_framework: {}
      - data_collection_plan: {}
    instructions: |
      Establish matrix analysis framework (power, interest, influence, attitude, values-alignment).
      Create structured stakeholder database template.
      Develop data collection planning methodology.
      Integrate public values inventory (Jørgensen & Bozeman framework).

  - id: "identification-1"
    name: "Primary Stakeholder Mapping"
    description: "Identify direct stakeholders with clear connections to the problem/solution"
    duration: "90 min"
    inputs:
      - stakeholder_initial
    outputs:
      - primary_stakeholders: []
    instructions: |
      Identify direct stakeholders: users (citizens/patients), suppliers (inputs), partners (collaboration), regulators (oversight).
      Classify with initial power assessment per stakeholder type.
      Document current relationship level (neutral, positive, negative).
      Prepare preliminary engagement strategy.

  - id: "identification-2"
    name: "Secondary Stakeholder Identification"
    description: "Identify indirect stakeholders with indirect influence on outcomes"
    duration: "90 min"
    inputs:
      - primary_stakeholders
    outputs:
      - secondary_stakeholders: []
      - influence_channels: {}
    instructions: |
      Identify indirect stakeholders: interest groups, media, experts, public/taxpayers.
      Analyze potential influence channels (social media, political, legal).
      Create comprehensive stakeholder ecosystem diagram.
      Assess reach and mobilization capacity per group.

  - id: "analysis-matrix"
    name: "Power & Interest Matrix Development"
    description: "Create power-interest matrix for stakeholder prioritization"
    duration: "120 min"
    inputs:
      - primary_stakeholders
      - secondary_stakeholders
    outputs:
      - power_interest_matrix: {}
      - prioritization_strategy: {}
    instructions: |
      Assess power level: High (can block/enforce changes), Low (limited influence).
      Assess interest level: High (strongly affected), Low (minimally affected).
      Plot in matrix: Key Players (high power/high interest), Keep Satisfied (high power/low interest), Keep Informed (low power/high interest), Monitor (low power/low interest).
      Develop engagement resource allocation based on matrix position.

  - id: "values-analysis"
    name: "Public Values-Stakeholder Alignment Analysis"
    description: "Deep analysis of value relationships and conflicts between stakeholders"
    agent-call: "cis-design-thinking-coach"
    duration: "4 hours"
    inputs:
      - power_interest_matrix
      - public_values_inventory
    outputs:
      - values_alignment_matrix: {}
      - values_conflicts: []
    instructions: |
      For each key stakeholder, conduct comprehensive values analysis:
      1. Values identification: Map against 72-value inventory, identify primary vs instrumental values
      2. Belangen-waarden mapping: Determine supportive vs conflicting value relationships
      3. Values interpretation analysis: Understand stakeholder-specific value framing differences
      4. Conflict assessment: Identify trade-offs and resolution strategies
      5. Leverage opportunities: Find values-based persuasion approaches

  - id: "profile-development"
    name: "Comprehensive Stakeholder Profile Development"
    description: "Create detailed profiles for key stakeholders including values relationships"
    agent-call: "cis-storyteller"
    duration: "180 min"
    inputs:
      - values_alignment_matrix
    outputs:
      - stakeholder_profiles: {}
      - engagement_recommendations: {}
    instructions: |
      Develop detailed profiles for each key stakeholder with:
      - Demographic data and reach
      - Interest analysis with evidence
      - Current position and attitude assessment
      - Public values relationship summary from alignment analysis
      - Influence strategy mapping
      - Preferred communication channels and messaging

  - id: "relationship-mapping"
    name: "Relationship & Coalition Analysis"
    description: "Analyze stakeholder relationships and potential coalition formations"
    duration: "120 min"
    inputs:
      - stakeholder_profiles
      - values_alignment_matrix
    outputs:
      - coalition_map: {}
      - relationship_network: {}
    instructions: |
      Map relationships between stakeholders incorporating values dimensions.
      Identify shared vs conflicting values interpretations.
      Analyze historical collaboration patterns based on values alignment.
      Identify potential coalitions around shared values.
      Assess power dynamics considering values-based influence.

  - id: "engagement-strategy"
    name: "Values-Based Engagement Strategy Development"
    description: "Develop stakeholder-specific engagement strategies using values insights"
    agent-call: "cis-design-thinking-coach"
    duration: "120 min"
    inputs:
      - stakeholder_profiles
      - coalition_map
    outputs:
      - engagement_strategy: {}
      - communication_plan: {}
    instructions: |
      Define engagement objectives aligned with stakeholder values.
      Select appropriate engagement methods based on values relationships.
      Develop communication strategies using values-based messaging.
      Create timeline and resource allocation for stakeholder engagement.

  - id: "communication-planning"
    name: "Stakeholder Communication Planning"
    description: "Create detailed communication plans with values-reframing where needed"
    agent-call: "cis-storyteller"
    duration: "120 min"
    inputs:
      - engagement_strategy
    outputs:
      - communication_matrix: {}
      - content_templates: {}
    instructions: |
      Develop key messages per stakeholder group using their values framework.
      Identify optimal communication channels based on values preferences.
      Create stakeholder-specific content incorporating values reframing.
      Develop feedback mechanisms for values dialogue.

  - id: "validation-review"
    name: "Stakeholder Analysis Validation"
    description: "Validate analysis completeness and accurateness including values aspects"
    duration: "60 min"
    inputs:
      - stakeholder_profiles
      - communication_matrix
    outputs:
      - validation_report: {}
      - improvement_actions: []
    instructions: |
      Cross-check values-belangen mapping against empirical evidence.
      Validate stakeholder interpretations through targeted verification.
      Test stakeholder strategy against historical cases.
      Assess overall impact on PVC and VSD frameworks.

  - id: "integration-synthesis"
    name: "PVC & VSD Integration Synthesis"
    description: "Link stakeholder analysis to broader PVC and VSD frameworks"
    duration: "60 min"
    inputs:
      - validation_report
    outputs:
      - pvc_stakeholder_integration: {}
      - vsd_empirical_basis: {}
    instructions: |
      Map stakeholders to PVC Team element with governance roles.
      Integrate values-belangen analysis into PVC Support element.
      Update PVC Environment with stakeholder-values dynamics.
      Document VSD empirical research foundation for next phases.

deliverables:
  - "Stakeholder Power-Interest Matrix": "Prioritized stakeholder map with engagement strategies"
  - "Public Values-Stakeholder Alignment Matrix": "Comprehensive values relationships analysis"
  - "Stakeholder Profile Database": "Detailed profiles with values-based engagement recommendations"
  - "Coalition Analysis Report": "Relationship mapping and strategic alliance opportunities"
  - "Values-Based Communication Plan": "Stakeholder-specific messaging and engagement strategies"
  - "PVC-VSD Integration Report": "Framework integration and empirical research foundation"

success-criteria:
  - All key stakeholders identified and mapped
  - Power-interest dynamics clearly understood
  - Public values relationships comprehensively analyzed
  - Engagement strategies values-informed and actionable
  - Communication plans tailored to stakeholder preferences
  - PVC-VSD integration points clearly established

validation-checklist:
  - [ ] Multi-level stakeholders represented (individual to systemic)
  - [ ] Power-interest analysis drives prioritization decisions
  - [ ] Values-conflicts identified and resolution strategies developed
  - [ ] Stakeholder profiles include values-leverage opportunities
  - [ ] Coalition potential assessed with values-based alliances
  - [ ] Engagement strategies address values-specific barriers
  - [ ] PVC-VSD empirical research foundation established
