name: "canvas-completion-validation"
description: "Complete canvas validation en stakeholder commitment voor Phase 2 transitie"

metadata:
  author: "Canvas Orchestrator"
  version: "1.0"
  last-updated: "2025-10-10"
  module: "value-ecosystem-design"
  framework: "PVC Toolkit - Completion & Validation"
  estimated-duration: "30-45 min"
  cis-integration: "storyteller"

variables:
  - user_name: "{user_name}"
  - complete_canvas: {}
  - stakeholder_commitment: {}
  - phase_2_readiness: {}
  - validation_report: {}
  - transition_package: {}
  - output_folder: "{output_folder}"

steps:
  - id: "canvas-completeness-check"
    name: "Complete Canvas Elements Validation"
    description: "Systematische check van alle 8 PVC elementen compleetheid"
    duration: "10 min"
    inputs: []
    outputs:
      - canvas_completeness: {}
    instructions: |
      PVC Toolkit Canvas Checklist validation:

      **Element-by-Element Check:**

      1. **Problem** → Clear definition with 5W + conditions ✅
      2. **Envisioned Future** → Compelling vision + scenarios ✅
      3. **Team** → Orchestrating + extended team defined ✅
      4. **Environment** → Context map + relevant trends ✅
      5. **Public Value Proposition** → Testable hypothesis ✅
      6. **Purpose** → Core values identified (Phase 1 level) ✅
      7. **Stakeholders** → Interests + basic mapping ✅
      8. **Capacity & Support** → Feasibility assessment ✅

      **Credibility Assessment:**
      - Plan neither laughably ambitious nor small ✅
      - Purpose, capacity, support aligned ✅
      - Coherent inter-element relationships ✅

  - id: "phase-2-readiness-evaluation"
    name: "Phase 2 Ecosystem Readiness Assessment"
    description: "Evaluate readiness voor diepgaande ecosystem realisatie"
    duration: "15 min"
    inputs:
      - canvas_completeness
    outputs:
      - phase_2_readiness: {}
    instructions: |
      Assess Phase 2 Readiness Criteria:

      **Technical Readiness:**
      - Canvas elements provide sufficient foundation?
      - Data gaps identified for Phase 2 scientific analysis?
      - Transition package contains required inputs?

      **Stakeholder Readiness:**
      - Commitment level sufficient voor Phase 2 intensiteit?
      - Key players ready voor diepgaande engagement?
      - Buy-in extended naar Phase 2 requirements?

      **Process Readiness:**
      - Orchestrating team prepared voor Phase 2 complexity?
      - Capacity basics form solid foundation voor detailed planning?
      - Risk assessment identifies Phase 2 critical paths?

      Determine confidence level voor Phase 2 succes.

  - id: "stakeholder-commitment-validation"
    name: "Final Stakeholder Commitment Validation"
    description: "Bevestig commitment van key stakeholders voor Phase 2 start"
    call-agent: "cis-storyteller"
    duration: "10 min"
    inputs:
      - phase_2_readiness
    outputs:
      - stakeholder_commitment: {}
    instructions: |
      CIS Storyteller facilitated commitment session:

      **Narrative Commitment Building:**
      - Present complete canvas as compelling story
      - Connect Phase 1 inspiration to Phase 2 transformation
      - Address stakeholder concerns with values-based narratives
      - Build shared vision	for successful Phase 2 execution

      **Commitment Validation:**
      - Confirm verbal/written commitment van key stakeholders
      - Identify commitment conditions en actions needed
      - Establish Phase 2 communication cadences
      - Document commitment signatures/approvals

      **Transition Communication:**
      - Phase 1 complete narrative
      - Phase 2 begins next cadence
      - Clear handoff van Canvas foundation naar Ecosystem design

deliverables:
  - "Complete Canvas Package": "Geïntegreerde PVC met alle 8 elementen"
  - "Phase 1 Completion Report": "Validation summary + achievements"
  - "Phase 2 Transition Package": "Inputs voor ecosystem orchestration"
  - "Stakeholder Commitment Records": "Commitment validations + conditions"

success-criteria:
  - Alle PVC elementen validated als compleet + coherent
  - Phase 2 readiness assessment confident over 70%
  - Stakeholder commitment gesecured voor Phase 2 initiatie
  - Transition package klaar voor ecosystem orchestrator handoff
  - Canvas foundation solide voor wetenschappelijke Phase 2

validation-checklist:
  - [ ] Canvas completeness: 8/8 elementen validated
  - [ ] Credibility check: Ambitious yet achievable
  - [ ] Coherence assessment: Elementen interconnected
  - [ ] Phase 2 readiness: Foundation sufficient
  - [ ] Stakeholder commitment: Key players committed
  - [ ] Transition package: Ecosystem workflow ready

template: "{installed_path}/canvas-completion-validation-template.md"
