name: "PVC Value Hierarchy Development Workflow"
description: "Develop comprehensive public values hierarchy with conflict resolution and design implications"

metadata:
  author: "PVC Agent"
  version: "1.0"
  last-updated: "2025-01-09"
  module: "BMM"
  framework: "VSD-Conceptual Research"
  estimated-duration: "1-2 days"
  cis-integration: "innovation-strategist, creative-problem-solver"

variables:
  - user_name: "{user_name}"
  - values_gap_analysis: {}
  - values_hierarchy: {}
  - conflict_resolution: {}
  - design_requirements: []
  - output_folder: "{output_folder}"

steps:
  - id: "gap-analysis"
    name: "Values Gap Analysis"
    description: "Identify missing values, norms, and requirements from Problem + Future analysis"
    duration: "45 min"
    inputs:
      - problem_statement_final
      - envisioned_future_final
    outputs:
      - values_gap_analysis: {}
    instructions: |
      Conduct comprehensive gap analysis:
      - Problem-to-Values Gap: Which values are violated vs required?
      - Future-to-Values Gap: Which new values emerge in solution?
      - Norms-to-Requirements Gap: Which design requirements are missing?
      - Cross-Context Gaps: Universal rights (UDHR), international standards

  - id: "primary-extraction"
    name: "Primary Values Extraction"
    description: "Identify most relevant public values from inventory based on problem context"
    duration: "60 min"
    inputs:
      - values_gap_analysis
      - public_values_inventory
    outputs:
      - primary_values: []
    instructions: |
      Map problem against Jørgensen & Bozeman 72-value inventory.
      Extract domain-specific values (healthcare: equity, quality, accessibility).
      Prioritize based on: impact, stakeholder salience, constitutional status.
      Cross-reference with gap analysis findings and empirical research.

  - id: "clustering-relations"
    name: "Values Clustering & Relationships Analysis"
    description: "Analyze relationships, synergies, and conflicts between identified values"
    duration: "60 min"
    inputs:
      - primary_values
    outputs:
      - values_relationships: {}
      - initial_conflicts: []
    instructions: |
      Create values affinity matrix: supportive vs conflicting relationships.
      Identify value clusters: core, context, stakeholder-specific values.
      Document initial conflicts: efficiency vs equity, privacy vs transparency.
      Analyze causal relationships and hierarchical dependencies.

  - id: "stakeholder-validation"
    name: "Stakeholder Values Validation"
    description: "Validate value priorities and interpretations against stakeholder perspectives"
    agent-call: "cis-innovation-strategist"
    duration: "60 min"
    inputs:
      - values_relationships
      - stakeholder_profiles
    outputs:
      - validated_values: []
      - interpretation_differences: {}
    instructions: |
      Cross-reference with Stakeholder Analysis values-alignment data.
      Identify stakeholder-specific value interpretations and priorities.
      Resolve discrepancies through stakeholder consultation.
      Update values list with empirical insights and gap analysis findings.

  - id: "translation-norms"
    name: "Values to Norms Translation"
    description: "Translate abstract values into concrete, measurable norms"
    agent-call: "cis-creative-problem-solver"
    duration: "90 min"
    inputs:
      - validated_values
    outputs:
      - value_norm_mappings: {}
    instructions: |
      For each value, generate derived norms:
      - Equity → "Iedereen heeft gelijke toegang ongeacht achtergrond"
      - Privacy → "Persoonsgegevens worden beschermd conform wetgeving"
      - Quality → "Dienstverlening voldoet aan professionele standaarden"
      Test norm measurability and actionability per stakeholder context.

  - id: "translation-requirements"
    name: "Norms to Design Requirements Translation"
    description: "Convert norms into specific, implementable design requirements"
    duration: "90 min"
    inputs:
      - value_norm_mappings
    outputs:
      - design_requirements: []
      - requirements_traceability: {}
    instructions: |
      Generate functional requirements:
      - "Gelijke toegang" → "Digitale toegankelijkheid voor alle burgers (WCAG 2.1 AA)"
      - "Privacy bescherming" → "Data minimalisatie en consent management systeem"
      Identify non-functional requirements (performance, security, compliance).
      Ensure requirements are verifiable and stakeholder-aligned.

  - id: "consistency-validation"
    name: "Hierarchy Consistency Validation"
    description: "Validate logical consistency and completeness of the value hierarchy"
    duration: "60 min"
    inputs:
      - design_requirements
    outputs:
      - consistency_report: {}
      - attention_points: []
    instructions: |
      Test vertical consistency: Requirements traceable to norms to values.
      Test horizontal consistency: No conflicting requirements within hierarchy.
      Identify weak links and gaps requiring additional analysis.
      Document assumptions and validation evidence.

  - id: "conflict-analysis"
    name: "Values Conflict Analysis & Resolution"
    description: "Identify and resolve conflicts between values and their design implications"
    agent-call: "cis-innovation-strategist"
    duration: "90 min"
    inputs:
      - consistency_report
    outputs:
      - conflict_resolution_strategies: {}
      - prioritized_resolutions: {}
    instructions: |
      Categorize conflicts: Direct (incompatible requirements), Indirect (competing priorities), Context-specific.
      Analyze stakeholder impact and ethical implications of each resolution.
      Develop resolution strategies: Prioritization, balancing mechanisms, scope limitations.
      Document trade-offs and rationale for ethical accountability.

  - id: "optimization-refinement"
    name: "Hierarchy Refinement & Optimization"
    description: "Optimize hierarchy based on conflict resolution and stakeholder alignment"
    duration: "60 min"
    inputs:
      - conflict_resolution_strategies
    outputs:
      - optimized_hierarchy: {}
      - refinement_justification: {}
    instructions: |
      Apply conflict resolutions to hierarchy structure.
      Add conditional logic for context-dependent values.
      Create sub-hierarchies for different stakeholder groups if needed.
      Establish priority rules for multi-value scenarios.

  - id: "stakeholder-alignment"
    name: "Stakeholder Values Alignment Validation"
    description: "Final validation of hierarchy against comprehensive stakeholder perspectives"
    duration: "60 min"
    inputs:
      - optimized_hierarchy
    outputs:
      - stakeholder_alignment_report: {}
      - final_hierarchy: {}
    instructions: |
      Present refined hierarchy to key stakeholders for feedback.
      Integrate stakeholder input on value interpretations and priorities.
      Resolve remaining conflicts through stakeholder dialogue.
      Finalize hierarchy with stakeholder buy-in and validation evidence.

  - id: "pvc-integration"
    name: "PVC Integration Mapping"
    description: "Map finalized value hierarchy to PVC framework elements"
    duration: "30 min"
    inputs:
      - final_hierarchy
    outputs:
      - pvc_values_integration: {}
      - framework_alignment_report: {}
    instructions: |
      Map hierarchy to PVC elements: Purpose (strategic values), Public Value Proposition (key requirements).
      Integrate design requirements into PVC Plan and Environment elements.
      Establish traceability between VSD technical research and PVC operationalization.
      Document integration points for other workflow phases.

deliverables:
  - "Values Gap Analysis Report": "Missing values, norms, and requirements identification"
  - "Primary Values Selection": "Justified selection of relevant public values"
  - "Values Relationships Matrix": "Synergies, conflicts, and clustering analysis"
  - "Complete Value Hierarchy": "Values → Norms → Design Requirements mapping"
  - "Conflict Resolution Strategy": "Ethical decisions and trade-off justifications"
  - "PVC Integration Mapping": "Framework alignment and traceability matrix"

success-criteria:
  - Public values comprehensively identified and prioritized
  - Value relationships and conflicts thoroughly analyzed
  - Hierarchy logically consistent and traceable
  - Design requirements specific and implementable
  - Stakeholder values perspectives integrated
  - PVC framework integration established

validation-checklist:
  - [ ] Gap analysis identifies missing elements across all levels
  - [ ] Primary values selection considers impact, stakeholder salience, and constitutional status
  - [ ] Values relationships analyzed for synergies and conflicts
  - [ ] Norms are concrete, measurable, and stakeholder-contextual
  - [ ] Design requirements are verifiable and implementation-ready
  - [ ] Hierarchy consistency validated through vertical and horizontal analysis
  - [ ] Conflicts identified and resolution strategies developed ethically
  - [ ] Stakeholder validation ensures empirical grounding
  - [ ] PVC integration establishes clear framework relationships
