name: "canvas-capacity-support-basics"
description: "Basic capacity en support assessment voor canvas feasibility check (Phase 1 niveau)"

metadata:
  author: "Canvas Orchestrator"
  version: "1.0"
  last-updated: "2025-10-10"
  module: "value-ecosystem-design"
  framework: "PVC Toolkit - Phase 1"
  estimated-duration: "30-45 min"
  cis-integration: "brainstorming-coach"

variables:
  - user_name: "{user_name}"
  - public_value_proposition: {}
  - orchestrating_team: {}
  - stakeholder_interests: []
  - capacity_basics: {}
  - support_basics: {}
  - feasibility_assessment: {}
  - output_folder: "{output_folder}"

steps:
  - id: "capacity-basics-assessment"
    name: "Capacity Basics Identification"
    description: "Basis assessment van benodigde middelen en vaardigheden"
    duration: "15 min"
    inputs:
      - public_value_proposition
      - orchestrating_team
    outputs:
      - capacity_basics: {}
    instructions: |
      Beoordeel basis capacity voor envisioned future:

      **People Capacity:**
      - Team size nodig voor minimum viable execution?
      - Key skills vereist voor core activities?
      - Expertise gaps die partnership/community behoeven?

      **Resource Capacity:**
      - Basis budget schatting voor proof-of-concept?
      - Physical/digital resources voor core activities?
      - Time commitment voor team members?

      **Organizational Capacity:**
      - Internal capabilities voor project hosting?
      - Partnerships/communities voor resource augmentation?

      Focus pragmatisch - haalbaarheid check, geen detailed planning.

  - id: "support-basics-assessment"
    name: "Support Basics Identification"
    description: "Basis assessment van benodigde toestemmingen en steun"
    duration: "15 min"
    inputs:
      - stakeholder_interests
      - capacity_basics
    outputs:
      - support_basics: {}
    instructions: |
      Identificeer support fundamenten:

      **Authorization Support:**
      - Welke stakeholder groepen moeten goedkeuren?
      - Minimum permissions voor proof-of-concept?
      - Political/societal buy-in vereist?

      **Financial Support:**
      - Basis funding voor initial phase?
      - In-kind contributions mogelijk?
      - Fundraising/community support realistic?

      **Societal Support:**
      - Public acceptability van approach?
      - Media/community perceptions?
      - Cultural fit met tijdgeest/trends?

      Basis identification - geen detailed strategy.

  - id: "feasibility-feasibility-assessment"
    name: "Pragmatic Feasibility Assessment"
    description: "Quick check of overall canvas feasibility"
    call-agent: "cis-brainstorming-coach"
    duration: "10 min"
    inputs:
      - capacity_basics
      - support_basics
      - stakeholder_interests
    outputs:
      - feasibility_assessment: {}
    instructions: |
      Beoordeel canvas feasibility voor Phase 2 commitment:

      **Go/No-Go Criteria:**
      - Essential capacity aanwezig/behaaldbaar in redelijke tijd?
      - Critical support verkrijgbaar van key stakeholders?
      - Overall risk acceptable voor Phase 1 completion?

      **Risk-Reward Balance:**
      - High-impact areas met lage obstruction?
      - Critical dependencies duidelijk?
      - Fallback options beschikbaar?

      Gebruik CIS Brainstorming Coach voor:
      - Creative resource solutions
      - Alternative funding approaches
      - Stakeholder influence mapping

      Deliver pragmatic advice - proceed/adjust/stop.

deliverables:
  - "Capacity Basics Assessment": "Essential resources en capabilities overview"
  - "Support Basics Assessment": "Key authorizations en financing needs"
  - "Feasibility Assessment": "Go/No-Go recommendation voor canvas completion"

success-criteria:
  - Capacity basics geïdentificeerd met realistic assessment
  - Support fundamentals geëvalueerd voor critical path
  - Feasibility pragmatically beoordeeld
  - CIS brainstorming input toegevoegd creative solutions
  - Stap naar canvas completion gemaakt

validation-checklist:
  - [ ] Capacity assessment realistic voor Phase 1 scope
  - [ ] Support basics terkend tegen stakeholder interests
  - [ ] Feasibility check balanced tussen optimism/pessimism
  - [ ] Creative solutions explored via brainstorming coach

template: "{installed_path}/capacity-support-basics-template.md"
